# Generated by Django 5.2.5 on 2025-10-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='statut',
            field=models.CharField(choices=[('scolariser', 'Scolariser'), ('exempter', 'Exempter')], default='scolariser', max_length=10, null=True),
        ),
    ]
