# Generated by Django 5.2.5 on 2025-10-08 16:01

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='contact_garduan',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CD', verbose_name='Contact du tuteur'),
        ),
    ]
