# Generated by Django 5.2.5 on 2025-10-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(max_length=255, verbose_name="Nom officiel de l'école")),
                ('number', models.CharField(blank=True, max_length=255, verbose_name="Numero d'agrément")),
                ('code', models.CharField(blank=True, max_length=255, verbose_name="code d'identification de l'école")),
                ('province', models.CharField(blank=True, max_length=255, verbose_name='Province Educationnelle')),
                ('statut', models.TextField(blank=True, verbose_name='Statut juridique')),
                ('promo', models.CharField(blank=True, max_length=255, verbose_name="Promoteur de l'école")),
            ],
            options={
                'db_table': 'hero',
            },
        ),
    ]
