# Generated by Django 5.2.5 on 2025-10-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dean',
            options={'verbose_name': "Titulaire d'option", 'verbose_name_plural': "Titulaires d'options"},
        ),
    ]
