# Generated by Django 5.2.5 on 2025-10-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profiles_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
