# Generated by Django 5.2.5 on 2025-11-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profiles_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default_bcIt09K.jpg', upload_to='avatar/'),
        ),
    ]
